### ISSUE TITLE
Strikethrough not working

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-git#1]
I'm not sure why, but sometimes the strikethrough formatting doesn't work.

It works in:
Hyperterm

It doesn't work in:
iTerm
Hyperterm in tmux
iTerm in tmux
Terminal

**Comment by trevordmiller** [comment]
@aharris88 I believe the parent application has to also support the `strike` property which is pretty new (`git 2.10`); not sure if there is any way to add it to tmux, iterm, or terminal. Let me know if you find out anything about it. I'm going to close this for now as I don't think I can do anything about it?
