### ISSUE TITLE
Upgrade to use nova-colors 2 versionControlGroups

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-git#2]
Update the color values to reflect [`nova-colors` 2 `versionControlGroup` meanings](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L45-L50) like this:

- [`added` on line 16](https://github.com/trevordmiller/nova-git/blob/master/assets/.gitconfig#L16) should be `green` instead of `cyan`
- [`new` on line 23](https://github.com/trevordmiller/nova-git/blob/master/assets/.gitconfig#L23) should be `green` instead of `cyan`
- [`changed` on line 17](https://github.com/trevordmiller/nova-git/blob/master/assets/.gitconfig#L17) should be `red bold` (orange) instead of just `red`

---

##### Background information

`.gitconfig` files use ANSI color variables like `red`, `cyan` etc so this assumes the user already has a Nova terminal plugin installed (like `nova-hyperterm` or `nova-iterm`) which updates these ANSI variable color values. Another note is that `.gitconfig` doesn't have access to the `bright{color}` versions of the ANSI color variables; instead, the `bold` version of the color is both bold and the bright version; so, for example, `red bold` is the same as `ansiColors.bright.red` (orange).

**Comment by johemst** [comment]
Thanks for updating the description 👍
