### ISSUE TITLE
Invalid example .gitconfig (Hyper.app on Mac OS X)

### ISSUE THREAD

**Issue by sprjr** [trevordmiller/nova-git#5]
Hello -

I've got the latest Hyper.app (0.8.1.737) with the Nova theme (which I love so far!) and finally updated the example colors for git as well. The default value in `[color "diff"]` seems to be throwing an error:

```
error: invalid color value: red strike
fatal: bad config variable 'color.diff.old' in file '/Users/stephenrivasjr/.gitconfig' at line 35
```

for any of the git commands. It seems to work fine with just `red` as the value, which is fine with me I just wanted to use things "as recommended" and wasn't sure if there was something wrong with this value. 

Something I'm doing wrong or won't work on my system most likely?

**Comment by trevordmiller** [comment]
@sprjr Hi Stephen! Thanks for using Nova. This looks to me like you don't have `git 2.10` or later? This is required for the `strike` property to work. Shouldn't have anything to do with HyperTerm. Try running `git --version` and if you get less than `git 2.10` you need to update. If you don't want to update (don't mind having the `strike` strikethrough styles on removed lines) you can also just remove the word `strike` and it should work :)

![image](https://cloud.githubusercontent.com/assets/5497885/19168352/0816c18e-8bcd-11e6-8bb5-92a00602fc2d.png)

**Comment by sprjr** [comment]
Apologies - I was on `2.8.4` and only scanned that line, I assumed a `2.x` branch would be fine. Thanks for clarifying.

**Comment by trevordmiller** [comment]
No worries :)
